# Generated by Django 4.1.7 on 2023-02-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stoke',
            new_name='stock',
        ),
    ]
